### ISSUE TITLE
pywin32-219.win32-py2.6.exe Install Fails in Wine

### ISSUE THREAD

**Issue by zeknox** [knightmare2600/ShadowBrokers#1]
Hey Knightmare2600-

Really appreciate you putting together some quick and dirty guides on getting this up and running.  Ran into an issue following your Linux guide that maybe you could shed some light on what the underlying issue may be.

Everything works within the instructions except when trying to install pywin32-219 for Python 2.6.

Command run to attempt to install pywin32 via wine on Kali. Error illustrated after install finishes.
<pre>
# wine /media/username//ShadowBrokers/Lost_In_Translation/pywin32-219.win32-py2.6.exe 
*** run_installscript: internal error 0xFFFFFFFF ***
</pre>

Error displayed at the end of the install within the GUI itself.
<pre>
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "C:\Python26\lib\tempfile.py", line 34, in <module>
    from random import Random as _Random
  File "C:\Python26\lib\random.py", line 871, in <module>
    _inst = Random()
  File "C:\Python26\lib\random.py", line 96, in __init__
    self.seed(x)
  File "C:\Python26\lib\random.py", line 110, in seed
    a = long(_hexlify(_urandom(16)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
</pre>

Any insight would be much appreciated.  Cheers.

**Comment by zeknox** [comment]
Wanted to provide an update here that the issue was present within Kali Linux OS.  I installed a fresh copy of Ubuntu 14.04.5 and followed the walkthrough without any issues.  Appreciate your guidance here.
